Oracle JavaScript Extension Toolkit (Oracle JET) is a complete yet modular JavaScript development toolkit helping
developers build engaging user interfaces. Based on industry standards and popular open-source frameworks,
Oracle JET further adds advanced functionality and services to help developer build better applications faster.

- https://oraclejet.org
- https://www.oracle.com/technetwork/developer-tools/jet/overview/index.html

== How to Build and Run This Project

  oject serve


== Create new project

  ojet create oject-starter

== How to Bootstrap OJET

You would need to configure RequireJS. See "js/main.js" as example.

https://docs.oracle.com/en/middleware/developer-tools/jet/6.2/develop/requirejs-oracle-jet-application.html

== OJET Data Binding Syntax

The {{...}} syntax indicates that the element’s value property will be updated in the element’s ViewModel if it’s changed. To prevent the attribute’s value from updating the corresponding ViewModel, use the [[...]] syntax.

NOTE: Please note that there should be no spaces between the braces when using the data bind syntax (e.g. some-attribute="[ [...] ]")

== TypeScript and Gruntfile Setup

The `grunt-ts` plugin does not support `tsconfig.json` "paths" options!

https://github.com/TypeStrong/grunt-ts/issues/339

Due to this, we have to invoke `tsc` and `ojet` separately.

This is fixed now! The trick is to setup 'tsconfig' as object with passThrough option set to true!

