## Fusion API
#    protected baseUrl = "https://day380-19201-sql-249h-irs.dq.lan/km/api/latest";
#    protected siteName = "day380_19201_sql_249h";
#    private integrationLogin: string = "iu_agent_desktop";
#    private integationPassword: string = "03D7E12D329A4B38AA34AC4454D3C6A4";
#    private userName: string = "administrator";
#    private userPassword: string = "Welcome@123";

# == 2 step Login

POST https://day380-19201-sql-249h-irs.dq.lan/km/api/latest/auth/integration/authorize
kmauthtoken: {"siteName" : "day380_19201_sql_249h"}
Accept: application/json
Content-Type: application/json

{
  "login": "iu_agent_desktop",
  "password": "03D7E12D329A4B38AA34AC4454D3C6A4"
}

> {% client.global.set("integrationUserToken", response.body.json.authenticationToken); %}

###

POST https://day380-19201-sql-249h-irs.dq.lan/km/api/latest/auth/authorize
kmauthtoken: {"siteName" : "day380_19201_sql_249h", "integrationUserToken": "ZGF5MzgwXzE5MjAxX3NxbF8yNDloOlBZZzYrTk5jdjB3T0pXQ05LcFIxOTB0R3ZMcWhkUnNyTTZ3UzNTdmRsK0VrNWo3c3FqVEw5Y2d4by9sMURmVEZCaGN2QUVHOFUycHMwRk5Xc3hNR2NSVWoxTzlpdlkyT0xSRit1WUFuZWx1aHhtSHpQZVZXNE1zMzhGZ3NpZHR6cjdKUUI4bEtzalhTc0tMdlozTTZPTkZKZXg0WlA5MnNQWVpUa05VSkZrMXpMeGpucjB6eXFNUjFDa2hMUVp2Sg=="}
Accept: application/json
Content-Type: application/x-www-form-urlencoded

userName=administrator&password=Welcome@123&userExternalType=ACCOUNT&siteName=day380_19201_sql_249h

> {% client.global.set("authenticationToken", response.body.json.authenticationToken); %}
###

# == Fetch content
GET https://day380-19201-sql-249h-irs.dq.lan/km/api/latest/content/D1FE85F51F2445DC96931C4EBCCCBE4B
kmauthtoken: {"siteName":"day380_19201_sql_249h", "integrationUserToken":"ZGF5MzgwXzE5MjAxX3NxbF8yNDloOlBZZzYrTk5jdjB3T0pXQ05LcFIxOTB0R3ZMcWhkUnNyTTZ3UzNTdmRsK0VrNWo3c3FqVEw5Y2d4by9sMURmVEZCaGN2QUVHOFUycHMwRk5Xc3hNR2NSVWoxTzlpdlkyT0xSRit1WUFuZWx1aHhtSHpQZVZXNE1zMzhGZ3NpZHR6cjdKUUI4bEtzalhTc0tMdlozTTZPTkZKZXg0WlA5MnNQWVpUa05VSkZrMXpMeGpucjB6eXFNUjFDa2hMUVp2Sg==", "userToken":"ereVIRkgCtK87w7t7SgOC4V4rbZy2vztsRL74/3EGW/oL1cnnedT7Vz2Ozy4gwc0FgeOP562IeiR35ar6qjvj07ebGwHRl+01FDCcJnBX8tUZZqOberh4hI0YDx6pBMwt5wKW5XDHIAA58ytdGGkwA=="}
Accept: application/json

###



