## OKCS API
https://fuscdrmsmc119-fa-ext.us.oracle.com/km/api/latest/content
Accept: application/json

###

https://fuscdrmsmc119-fa-ext.us.oracle.com:443/km/api/latest/content/2299094906414FBF8692CBB2AE466248
Accept: application/json

###


https://fuscdrmsmc119-fa-ext.us.oracle.com:443/km/api/latest/users/300100092862180
Authorization: Basic kmtest1 Welcome1
Accept: application/json

